defaults:
  - dataset: re10k
  - optional dataset/view_sampler_dataset_specific_config: ${dataset/view_sampler}_${dataset}
  - model/encoder: costvolume
  - model/decoder: splatting_cuda
  - model/refiner: refinement_1
  - loss: [mse]
  - experiment: re10k

# defaults:
#   - dataset: panoptic
#   - optional dataset/view_sampler_dataset_specific_config: ${dataset/view_sampler}_${dataset}
#   - model/encoder: costvolume
#   - model/decoder: splatting_cuda
#   - loss: [mse]
#   - experiment: panoptic

wandb:
  project: MV_Thesis
  entity: rucci-2053183
  name: Mv_Refinement_UniSampling_GaussianSpace_KL
  mode: online
  id: null

mode: train #  here train means knowledge distillation 
enable_refinement: true

dataset:
  overfit_to_scene: null
  view_sampler:
    index_path: assets/evaluation_index_re10k.json

data_loader:
  # Avoid having to spin up new processes to print out visualizations.
  train:
    num_workers: 10
    persistent_workers: true
    batch_size: 1
    seed: 1234
  test:
    num_workers: 1
    persistent_workers: false
    batch_size: 1
    seed: 2345
  val:
    num_workers: 1
    persistent_workers: true
    batch_size: 1
    seed: 3456

optimizer:
  lr: 2.e-4
  warm_up_steps: 2000
  cosine_lr: true

checkpointing:
  # load: outputs/2025-03-10/20-23-04/checkpoints/best_train_loss-v1.ckpt
  load: checkpoints/re10k.ckpt
  # load: outputs/2025-02-20/18-50-57/checkpoints/best_train_loss-v1.ckpt
  # load: outputs/2025-02-20/18-50-57/checkpoints/best_val_psnr.ckpt
  # load: outputs/2025-02-20/18-50-57/checkpoints/best_val_psnr.ckpt
  # load: outputs/2025-02-20/18-50-57/checkpoints/best_train_loss.ckpt
  # load: outputs/2025-02-20/18-50-57/checkpoints/best_val_psnr-v1.ckpt
  every_n_train_steps: 10  # 5000
  save_top_k: -1
  pretrained_model: null
  resume: true

train:
  depth_mode: null
  extended_visualization: false
  print_log_every_n_steps: 1

test:
  output_path: outputs/test
  compute_scores: true
  eval_time_skip_steps: 0
  save_image: true
  save_video: false

seed: 111123

trainer:
  max_steps: -1
  val_check_interval: 0.5
  gradient_clip_val: 0.5
  num_sanity_val_steps: 2
  num_nodes: 1

output_dir: null
