defaults:
  - view_sampler: evaluation


name: re10k
roots: [datasets/re10k]
make_baseline_1: true
augment: true

image_shape: [180, 320]
background_color: [0.0, 0.0, 0.0]
cameras_are_circular: false

baseline_epsilon: 1e-3
max_fov: 100.0

skip_bad_shape: true
near: -1.
far: -1.
baseline_scale_bounds: true
shuffle_val: true
test_len: -1
test_chunk_interval: 1
test_times_per_scene: 1

refinement: true
refinement_cfg:
  name: refinement_bounded
  min_distance_between_refinement_views: 45
  max_distance_between_refinement_views: 192
  min_distance_to_refinement_views: 0
  warm_up_steps: 150_000
  initial_min_distance_between_refinement_views: 25
  initial_max_distance_between_refinement_views: 45
  num_refinement_views: 4
  num_steps: 100