defaults:
  - view_sampler: evaluation # bounded, evaluation


name: re10k
roots: [datasets/re10k]
make_baseline_1: true
augment: true

image_shape: [180, 320]
background_color: [0.0, 0.0, 0.0]
cameras_are_circular: false

baseline_epsilon: 1e-3
max_fov: 100.0

skip_bad_shape: true
near: -1.
far: -1.
baseline_scale_bounds: true
shuffle_val: true
test_len: -1
test_chunk_interval: 1
test_times_per_scene: 1

refinement: true
refinement_cfg:
  name: refinement_camera_proximity # refinement_context, refinement_camera_proximity, refinement_camera_K_E, refinement_random # ---------- 
  num_refinement_views: 4
  index_path: assets/evaluation_index_re10k.json # when using refinement_context
